spring:
  application:
    name: servidor-zull
    
server:
  port: 8090
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    ruta-productos:
      path: /sproductos/**
      service-id: servicio-productos
    ruta-pedidos:
      path: /spedidos/**
      service-id: servicio-pedidos